markdown: redcarpet
highlighter: 
permalink: /:title

url: https://krsandeep98.github.io
baseurl: 

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed

